# Site settings
title: Premsai blogs
email: 
description: "Technical explorations in web development, backend systems, AI/ML, and developer tooling — built by a developer, for developers."
baseurl: "/blogs"
url: "http://sajjapremsai.github.io"
twitter_username: Premsai_Sajja
github_username:  SajjaPremsai

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
