# Site settings
title: Premsai blogs
email: 
description: "Software Developer"
baseurl: "/blogs"
url: "http://sajjapremsai.github.io"
twitter_username: Premsai_Sajja
github_username:  SajjaPremsai

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
